In [1]:
# importation des modules
import pandas as pd
import numpy as np

On importe directement les données pré-traitées : pour plus de détails quand à la méthode employée, voir le notebook `preprocess.ipynb`.

In [2]:
# chargement des données et visualisation
# questions spontanées
data_spon = pd.read_csv("../data/tf_idf_spon.csv")
data_spon.head()

,Unnamed: 0,a,a fait,activ,ah,aim,aim bien,allez,alor,appart,...,villag,voi,voyezvous,vrai,vu,ça,ça ça,ète,élev,étud
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.600654,0.0,0.0,0.0,0.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.660388,0.0,0.0,0.0,0.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.791995,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [3]:
# questions préparées
data_prep = pd.read_csv("../data/tf_idf_prep.csv")
data_prep.head()

,Unnamed: 0,a,a fait,activ,ah,aim,aim bien,allez,alor,appart,...,villag,voi,voyezvous,vrai,vu,ça,ça ça,ète,élev,étud
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.600654,0.0,0.0,0.0,0.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.660388,0.0,0.0,0.0,0.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.791995,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

## Test de l'algorithme des *k-moyennes*
À l'aide des modules sklearn & nltk.

In [4]:
# importation des modules nécessaires
from nltk.stem.snowball import FrenchStemmer
import sklearn
from sklearn import cluster
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
import numpy as np
from numpy import concatenate
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
data_spon = pd.read_csv("../data/tf_idf_spon.csv")
data_prep = pd.read_csv("../data/tf_idf_prep.csv")

In [8]:
def data_transform(train):
    tokenizer = RegexpTokenizer(r"\w+")
    stemmer = FrenchStemmer()
    stopword_fr = stopwords.words('french')
    vectorizer = TfidfVectorizer(tokenizer=tokenizer.tokenize, stop_words=stopwords_fr,
                                  analyzer="word", ngram_range=(1, 3), min_df=5, max_df=0.9)
    X = vectorizer.fit_transform(train)
    n_clusters = 2
    random_state = 1
    clf = KMeans(n_clusters=n_clusters, random_state=random_state)
    data = clf.fit(X)
    centroids = clf.cluster_centers_
    # we want to transform the rows and the centroids
    everything = concatenate((X.todense(), centroids))
    return everything

In [ ]:
def run_tsne(data):
    tsne_init = 'pca'  # could also be 'random'
    tsne_perplexity = 20.0
    tsne_early_exaggeration = 4.0
    tsne_learning_rate = 10
    model = TSNE(n_components=2, random_state=random_state, init=tsne_init,
             perplexity=tsne_perplexity,
             early_exaggeration=tsne_early_exaggeration, learning_rate=tsne_learning_rate)
    transformed_everything = model.fit_transform(data)
    return transformed_everything

{2: KMeans(n_clusters=2, n_init=10, random_state=1)}